package com.android.zj.ai.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneDataDaoConfig;

    private final PhoneDataDao phoneDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneDataDaoConfig = daoConfigMap.get(PhoneDataDao.class).clone();
        phoneDataDaoConfig.initIdentityScope(type);

        phoneDataDao = new PhoneDataDao(phoneDataDaoConfig, this);

        registerDao(PhoneData.class, phoneDataDao);
    }
    
    public void clear() {
        phoneDataDaoConfig.clearIdentityScope();
    }

    public PhoneDataDao getPhoneDataDao() {
        return phoneDataDao;
    }

}
